CREATE DATABASE IF NOT EXISTS appsahdb;

drop table if exists appsahdb.MASTER_CONTACT_CATEGORY;
drop table if exists appsahdb.MASTER_MEMCAT;
drop table if exists appsahdb.MEMBER;
drop table if exists appsahdb.CONTACT;
drop table if exists appsahdb.TOP_MENU;

CREATE TABLE appsahdb.MASTER_CONTACT_CATEGORY(ID CHAR(5) NOT NULL, NAME VARCHAR(128) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.MASTER_MEMCAT(ID CHAR(5) NOT NULL, NAME VARCHAR(128) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.MEMBER(ID CHAR(10) NOT NULL, NAME VARCHAR(128) NOT NULL, MEMCAT CHAR(5) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID), FOREIGN KEY(MEMCAT) REFERENCES appsahdb.MASTER_MEMCAT(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.CONTACT(ID INTEGER AUTO_INCREMENT, CONTENTS VARCHAR(256) NOT NULL, CATEGORY CHAR(5) NOT NULL, ADDMEM CHAR(10) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, DATE VARCHAR(32), PRIMARY KEY(ID), FOREIGN KEY(CATEGORY) REFERENCES appsahdb.MASTER_CONTACT_CATEGORY(ID), FOREIGN KEY(ADDMEM) REFERENCES appsahdb.MEMBER(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.TOP_MENU(ID CHAR(10) NOT NULL, PARENT_ID CHAR(10), NAME VARCHAR(128) NOT NULL, URL VARCHAR(1024), RESTRICTER CHAR(5), DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID)) ENGINE=INNODB;
