CREATE DATABASE IF NOT EXISTS appsahdb;

drop table if exists appsahdb.MASTER_CONTACT_CATEGORY;
drop table if exists appsahdb.MASTER_MEMCAT;
drop table if exists appsahdb.MEMBER;
drop table if exists appsahdb.CONTACT;
drop table if exists appsahdb.TOP_MENU;

CREATE TABLE appsahdb.MASTER_CONTACT_CATEGORY(ID CHAR(5) NOT NULL, NAME VARCHAR(128) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.MASTER_MEMCAT(ID CHAR(5) NOT NULL, NAME VARCHAR(128) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.MEMBER(ID CHAR(10) NOT NULL, NAME VARCHAR(128) NOT NULL, MEMCAT CHAR(5) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, PRIMARY KEY(ID), FOREIGN KEY(MEMCAT) REFERENCES appsahdb.MASTER_MEMCAT(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.CONTACT(ID INTEGER AUTO_INCREMENT, CONTENTS VARCHAR(256) NOT NULL, CATEGORY CHAR(5) NOT NULL, ADDMEM CHAR(10) NOT NULL, DELFLAG BOOLEAN DEFAULT 0, DATE VARCHAR(32), PRIMARY KEY(ID), FOREIGN KEY(CATEGORY) REFERENCES appsahdb.MASTER_CONTACT_CATEGORY(ID), FOREIGN KEY(ADDMEM) REFERENCES appsahdb.MEMBER(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.TOP_MENU(ID CHAR(10) NOT NULL, PARENT_ID CHAR(10), NAME VARCHAR(128) NOT NULL, MENUCONTENTS MEDIUMBLOB, RESTRICTER CHAR(5), DELFLAG BOOLEAN DEFAULT 0, LASTUPMEMBER CHAR(10), PRIMARY KEY(ID), LASTUPDATE VARCHAR(32), FOREIGN KEY(LASTUPMEMBER) REFERENCES appsahdb.MEMBER(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.MASTER_FREESOFT_CATEGORY(ID CHAR(5) NOT NULL, NAME VARCHAR(256) NOT NULL, MEMO VARCHAR(1024), LASTUPDATE VARCHAR(32), DELFLAG BOOLEAN, PRIMARY KEY(ID)) ENGINE=INNODB;

CREATE TABLE appsahdb.FREESOFT(ID INTEGER AUTO_INCREMENT, NAME VARCHAR(256) NOT NULL, CATEGORY_ID CHAR(5), VERSION CHAR(24), FILEPATH VARCHAR(1024), MEMO VARCHAR(1024), ADDMEM CHAR(10), ADDDATE VARCHAR(32), DELFLAG BOOLEAN, PRIMARY KEY(ID), FOREIGN KEY(ADDMEM) REFERENCES appsahdb.MEMBER(ID), FOREIGN KEY(CATEGORY_ID) REFERENCES appsahdb.MASTER_FREESOFT_CATEGORY(ID)) ENGINE=INNODB;