INSERT INTO MEMBER VALUES('aa', '多木', '2', 0);
INSERT INTO MEMBER VALUES('bb', '黒田', '3', 0);
INSERT INTO MEMBER VALUES('vv', '稲田', '1', 0);
INSERT INTO MEMBER VALUES('dd', '小林', '1', 0);
INSERT INTO MEMBER VALUES('ee', '荒野', '1', 0);
INSERT INTO MEMBER VALUES('ff', '牧島', '1', 0);
INSERT INTO MEMBER VALUES('gg', '渡部', '1', 0);